- hosts: all
  remote_user: edureka
  gather_facts: no

  tasks:
    - name: building docker image using war file
      command: docker build -t abctech-docker-image .
      args:
        chdir: /home/edureka/vaibhav/deployFiles

