- hosts: all
  remote_user: edureka
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /home/edureka/ansible_project1
        state: directory
        owner: edureka
        group: edureka
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /home/edureka/ansible_project1
        owner: edureka
        group: edureka
        mode: '0644'
    - name: build container image
      docker_image:
        name: 3af4f921caafb0274b20b808af55b1493fe80a1d:latest
        build:
          path: /home/edureka/ansible_project1
        state: present
