- hosts: all
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: /home/edureka/ansible_project
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: /home/edureka/ansible_project
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: democontainer:v1.0
        build:
          path: /home/edureka/ansible_project
          source: build
        state: present
