- hosts: all
  remote_user: edureka
  gather_facts: no

  tasks:
    - name: building docker image using war file
      command: docker build -t abctech-docker-image .
      args:
        chdir: /home/edureka/ansible_repo/Ansible_docker

    - name: building docker container out of image
      command: docker run -d --name abctech-docker-container -p 1585:8080 abctech-docker-image

